import type { AppKnowledgeCard } from "@/types/knowledge";

export const categoryRotation = [
  { day: "周一", category: "自然科学" },
  { day: "周二", category: "工程技术" },
  { day: "周三", category: "人文社科" },
  { day: "周四", category: "商业金融" },
  { day: "周五", category: "历史文明" },
  { day: "周六", category: "艺术设计" },
  { day: "周日", category: "综合冷知识" },
];

export const mockCards: AppKnowledgeCard[] = [
  {
    id: "card-001",
    title: "EUV 光刻机为什么是芯片产业链瓶颈",
    subtitle: "一张图看懂先进制程背后的关键设备",
    category: "工程技术",
    subCategory: "半导体制造",
    difficulty: "入门",
    cardDate: "2026-04-29",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop",
    summary: "EUV 光刻机利用极紫外光，把极其微细的电路图案转移到晶圆表面，是先进芯片制造的核心设备。",
    keywords: ["EUV", "晶圆", "掩膜版", "光刻胶", "制程节点"],
    completed: false,
    favorite: true,
    needReview: false,
    content: {
      title: "EUV 光刻机为什么是芯片产业链瓶颈",
      subtitle: "一张图看懂先进制程背后的关键设备",
      category: "工程技术",
      subCategory: "半导体制造",
      difficulty: "入门",
      summary: "EUV 光刻机利用极紫外光，把极其微细的电路图案转移到晶圆表面，是先进芯片制造的核心设备。",
      coreMechanism: "它通过光源、掩膜版、投影光学系统、光刻胶晶圆、显影与蚀刻等环节协同工作，把电路图案精确转移到晶圆上。",
      whyImportant: ["波长更短，能刻更细的电路线条。", "先进制程如 7nm、5nm 高度依赖它。", "设备极其复杂，制造门槛极高。", "高端设备稀缺，会限制芯片产能扩张。"],
      processSteps: [
        { step: 1, title: "光源产生", desc: "先生成极紫外光源。" },
        { step: 2, title: "图案投影", desc: "将掩膜版图案缩小投射到晶圆上。" },
        { step: 3, title: "显影蚀刻", desc: "通过显影和蚀刻形成精细电路。" },
      ],
      keywords: [
        { term: "EUV", desc: "极紫外光刻技术。" },
        { term: "晶圆", desc: "芯片制造的基础材料。" },
        { term: "掩膜版", desc: "承载电路图案的模板。" },
        { term: "光刻胶", desc: "对光敏感的材料。" },
        { term: "制程节点", desc: "描述芯片精细程度的指标。" },
      ],
      misconception: {
        title: "不是所有芯片都需要 EUV",
        content: "只有先进制程芯片高度依赖 EUV，成熟制程仍可使用其他光刻技术。",
      },
      financeAngle: "EUV 设备昂贵且供应稀缺，会影响晶圆厂资本开支、折旧压力、扩产节奏，以及先进制程芯片的供给能力。",
      memoryHooks: ["波长越短，线条越细。", "高端设备稀缺会卡住整个产业链。"],
      thinkingQuestions: [
        { level: "概念理解", question: "为什么 EUV 比传统光刻更适合先进制程？", answer: "因为 EUV 使用更短波长的极紫外光，理论上可以刻画更细的电路线条，从而支持更高密度、更先进的芯片制程。", keyPoint: "理解波长、线宽和先进制程之间的关系" },
        { level: "因果分析", question: "为什么一台设备的稀缺会影响整个芯片产业链？", answer: "因为高端光刻机是先进芯片制造中的关键瓶颈设备。如果设备供给有限，晶圆厂即使有资金和厂房，也难以快速扩大先进制程产能，进而影响芯片设计公司、封测厂和下游电子产品厂商。", keyPoint: "理解关键设备瓶颈如何传导到产业链" },
        { level: "迁移应用", question: "如果 EUV 设备供应大幅增加，哪些企业可能最先受益？", answer: "最先受益的通常是先进制程晶圆厂，其次是依赖先进制程的芯片设计公司，再往后是服务器、AI 芯片、手机芯片等下游应用厂商。", keyPoint: "把技术瓶颈迁移到商业和产业链分析" },
      ],
      conclusion: "EUV 光刻机是先进制程的咽喉，其稀缺与复杂性直接制约芯片产业链的上限。",
    },
  },
  {
    id: "card-002",
    title: "海底热液喷口如何孕育生命",
    subtitle: "极端环境里的生命起源线索",
    category: "自然科学",
    subCategory: "海洋地质",
    difficulty: "入门",
    cardDate: "2026-04-28",
    imageUrl: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?q=80&w=1200&auto=format&fit=crop",
    summary: "海底热液喷口释放富含矿物质的高温流体，为不依赖阳光的生命系统提供能量来源。",
    keywords: ["热液喷口", "化能合成", "极端生命", "矿物质"],
    completed: true,
    favorite: false,
    needReview: true,
    content: {
      title: "海底热液喷口如何孕育生命",
      subtitle: "极端环境里的生命起源线索",
      category: "自然科学",
      subCategory: "海洋地质",
      difficulty: "入门",
      summary: "海底热液喷口释放富含矿物质的高温流体，为不依赖阳光的生命系统提供能量来源。",
      coreMechanism: "地壳裂隙中的海水被岩浆加热后携带矿物质喷出，微生物利用化学能合成有机物，形成独立生态系统。",
      whyImportant: ["说明生命并不一定依赖阳光。", "为生命起源研究提供线索。", "极端生命研究可延伸到外星生命探索。"],
      processSteps: [
        { step: 1, title: "海水渗入", desc: "海水沿地壳裂缝渗入深处。" },
        { step: 2, title: "高温加热", desc: "岩浆将海水加热并溶解矿物质。" },
        { step: 3, title: "微生物利用", desc: "微生物通过化能合成构建生态系统。" },
      ],
      keywords: [
        { term: "热液喷口", desc: "海底喷出高温矿物流体的地质结构。" },
        { term: "化能合成", desc: "利用化学能制造有机物。" },
        { term: "极端生命", desc: "适应极端环境的生命形式。" },
        { term: "矿物质", desc: "提供化学能和环境支撑。" },
      ],
      misconception: {
        title: "生命并非一定依赖阳光",
        content: "热液喷口生态系统说明化学能也可以成为生命系统的基础。",
      },
      financeAngle: "深海矿产、海洋科研装备和极端环境探测技术，会影响未来资源开发与高端装备投入。",
      memoryHooks: ["没有阳光，也可能有生命。", "极端环境可能隐藏起源线索。"],
      thinkingQuestions: [
        { level: "概念理解", question: "热液喷口生态系统为什么可以不依赖阳光？", answer: "因为底层微生物可以通过化能合成利用化学能制造有机物。", keyPoint: "理解化能合成" },
        { level: "因果分析", question: "为什么热液喷口会被用于研究生命起源？", answer: "因为它提供了早期地球可能存在的能量、矿物界面和封闭微环境。", keyPoint: "连接环境条件与生命起源假说" },
        { level: "迁移应用", question: "这类研究为什么会影响外星生命探索？", answer: "它提示某些星球即使没有阳光，也可能在地下海洋或热液环境中孕育生命。", keyPoint: "把地球极端生命迁移到天体探索" },
      ],
      conclusion: "热液喷口说明生命可以依靠化学能建立生态系统。",
    },
  },
  {
    id: "card-003",
    title: "航空发动机为什么像卖打印机",
    subtitle: "设备销售与长期服务收入的商业模式",
    category: "商业金融",
    subCategory: "商业模式",
    difficulty: "进阶",
    cardDate: "2026-04-27",
    imageUrl: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=1200&auto=format&fit=crop",
    summary: "航空发动机厂商不仅卖设备，更依靠长期维修、零部件和服务合同获得持续收入。",
    keywords: ["剃刀模式", "MRO", "服务收入", "生命周期"],
    completed: true,
    favorite: true,
    needReview: false,
    content: {
      title: "航空发动机为什么像卖打印机",
      subtitle: "设备销售与长期服务收入的商业模式",
      category: "商业金融",
      subCategory: "商业模式",
      difficulty: "进阶",
      summary: "航空发动机厂商不仅卖设备，更依靠长期维修、零部件和服务合同获得持续收入。",
      coreMechanism: "发动机初始销售可能利润有限，但后续维护、检修、备件和按小时计费服务构成长期现金流。",
      whyImportant: ["客户绑定周期长。", "售后利润池大。", "资产安全要求高，替代成本高。"],
      processSteps: [
        { step: 1, title: "初始销售", desc: "先完成发动机装机销售。" },
        { step: 2, title: "长期维护", desc: "维修、检修和更换零部件带来持续收入。" },
        { step: 3, title: "服务合同", desc: "按小时计费等服务合同增强现金流稳定性。" },
      ],
      keywords: [
        { term: "剃刀模式", desc: "先卖设备，再赚后续耗材和服务的钱。" },
        { term: "MRO", desc: "维护、维修与大修业务。" },
        { term: "服务收入", desc: "设备售后长期获取的收入。" },
        { term: "生命周期", desc: "从装机到退役的长期服务周期。" },
      ],
      misconception: {
        title: "设备收入不是全部利润来源",
        content: "很多高价值设备业务真正的利润在售后服务，而不是首次销售。",
      },
      financeAngle: "这类业务的价值不只看设备毛利，还要看装机量、维修合同、存量机队和长期服务利润率。",
      memoryHooks: ["先装机，后服务。", "客户越换不了，服务价值越高。"],
      thinkingQuestions: [
        { level: "概念理解", question: "为什么航空发动机可以类比打印机商业模式？", answer: "因为初始设备只是入口，后续耗材、维护和服务才是长期收入来源。", keyPoint: "理解设备入口与服务收入" },
        { level: "因果分析", question: "为什么航空发动机客户替换供应商很难？", answer: "因为安全认证、维修体系、飞行数据和机型适配都形成高转换成本。", keyPoint: "理解客户锁定" },
        { level: "迁移应用", question: "分析这类公司时应重点看哪些指标？", answer: "应关注装机量、服务合同覆盖率、维修收入占比、存量机队规模和现金流稳定性。", keyPoint: "从商业模式迁移到财务分析" },
      ],
      conclusion: "航空发动机的核心价值往往藏在长期服务网络中。",
    },
  },
];
